### ISSUE TITLE
starting off on ur little project

### ISSUE THREAD

**Issue by ghost** [AR-DEV-1/MC1.19.4JAR#1]
If you want to REALLY do this, then i suggest u start with the EaglercraftX source code, as it's extremely helpful.

**Comment by Shakai-Dev** [comment]
Bro this is only The MC 1.19.4 Jar

**Comment by ghost** [comment]
well then use MCP reborn.

**Comment by Shakai-Dev** [comment]
lol i hav other projects

**Comment by ghost** [comment]
ah ok
